language: ruby
only:
  - master
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - "RAILS_VERSION=\"~> 3.0.0\""
    - "RAILS_VERSION=\"~> 3.1.0\""
    - "RAILS_VERSION=\"~> 3.2.0\""
    - "RAILS_VERSION=\"~> 4.0.0\""